# Generated by Django 2.0.5 on 2018-10-07 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poles', '0002_auto_20181007_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=0, to=settings.AUTH_USER_MODEL),
        ),
    ]
